### ISSUE TITLE
"When not to use Depot?" section missing

### ISSUE THREAD

**Issue by tedmiston** [depot/docs#14]
In the Introduction ToC, there's a reference to a "When not to use Depot?" ID, but that ID and section appear not to exist.

https://github.com/depot/docs/blob/0b289f28d6541cc0c0808a00593610ea50cc8e55/content/overview/index.mdx#L12

https://github.com/search?q=repo%3Adepot%2Fdocs%20%22When%20not%20to%20use%20Depot%3F%22&type=code

Although one could trivially negate the 3 points under "When to use Depot?", it would be nice to have something more insightful here, as I have noticed the rest of the docs and blog posts tend to be.

Thank you,
Taylor

**Comment by kylegalbraith** [comment]
Thanks for flagging. We've added this back.
